import type { Ticket } from "./types";

export const initialTickets: Ticket[] = [
  {
    id: 1008,
    title: "Shared folder access denied",
    employee: "employee@company.com",
    description: "I cannot open the shared finance folder even though I was added to the team.",
    category: "Account & Access",
    priority: "High",
    status: "Open",
    issue: "Folder Permission",
    confidence: 93,
    resolution: ["Confirm your account is in the correct group.", "Sign out and sign back in.", "Request access from the folder owner.", "Contact IT if access is still denied."],
  },
  {
    id: 1007,
    title: "Python installation request",
    employee: "employee@company.com",
    description: "Please install Python on my work laptop for an approved project.",
    category: "Software",
    priority: "Low",
    status: "Open",
    issue: "Software Installation",
    confidence: 91,
    resolution: ["Confirm the required Python version.", "Download it from the approved software portal.", "Run the installer with IT approval.", "Restart your terminal after installation."],
  },
  {
    id: 1006,
    title: "Keyboard not responding",
    employee: "employee@company.com",
    description: "Several keys on my laptop keyboard have stopped responding.",
    category: "Hardware",
    priority: "Low",
    status: "Resolved",
    issue: "Keyboard Issue",
    confidence: 92,
    resolution: ["Restart the laptop.", "Reconnect the keyboard if external.", "Check for physical debris.", "Contact IT for a replacement if needed."],
  },
  {
    id: 1005,
    title: "Office Wi-Fi disconnecting",
    employee: "employee@company.com",
    description: "My laptop repeatedly disconnects from the office Wi-Fi.",
    category: "Network",
    priority: "Medium",
    status: "Open",
    issue: "Wi-Fi Connectivity",
    confidence: 90,
    resolution: ["Forget and reconnect to the Wi-Fi network.", "Restart your device.", "Move closer to an access point.", "Contact IT if the issue continues."],
  },
  {
    id: 1004,
    title: "Chrome keeps crashing",
    employee: "employee@company.com",
    description: "Google Chrome closes unexpectedly whenever I open multiple tabs.",
    category: "Software",
    priority: "Medium",
    status: "Resolved",
    issue: "Browser Crash",
    confidence: 93,
    resolution: ["Close all Chrome windows.", "Disable recently added extensions.", "Update Chrome to the latest version.", "Reinstall Chrome if crashing continues."],
  },
  {
    id: 1003,
    title: "Unable to login",
    employee: "employee@company.com",
    description: "My company login is not accepting my password this morning.",
    category: "Account & Access",
    priority: "High",
    status: "Open",
    issue: "Login Failure",
    confidence: 95,
    resolution: ["Check that Caps Lock is off.", "Reset your password through the portal.", "Try signing in again.", "Contact IT if your account remains locked."],
  },
  {
    id: 1002,
    title: "Laptop screen flickering",
    employee: "employee@company.com",
    description: "The laptop display flickers intermittently during video calls.",
    category: "Hardware",
    priority: "Medium",
    status: "Open",
    issue: "Display Issue",
    confidence: 92,
    resolution: ["Restart the laptop.", "Check display cables and power.", "Update the display driver.", "Contact IT if the screen continues to flicker."],
  },
  {
    id: 1001,
    title: "VPN not connecting",
    employee: "employee@company.com",
    description: "Unable to connect to the company VPN from home.",
    category: "Network",
    priority: "High",
    status: "Open",
    issue: "VPN Connectivity",
    confidence: 94,
    resolution: ["Check your internet connection.", "Restart the VPN client.", "Verify your credentials.", "Try connecting again.", "Contact IT support if the problem continues."],
  },
];
